### ISSUE TITLE
Issue with "Reconstruction Space Generation" step

### ISSUE THREAD

**Issue by Rum980** [gift-surg/NiftyMIC#30]
I am in the "Reconstruction Space Generation" step. While running reconstruction pipeline I received the following error. Would anyone be able to explain the error and how to resolve? I am using Python 3.10.

Code:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/niftymic_reconstruct_volume", line 33, in <module>
    sys.exit(load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_reconstruct_volume')())
  File "/NiftyMIC/niftymic/application/reconstruct_volume.py", line 314, in main
    joint_image_mask_builder.run()
  File "/NiftyMIC/niftymic/utilities/joint_image_mask_builder.py", line 52, in run
    mask_sitk = thresholder.Execute(mask_sitk, 0, 0.5, 0, 1)
**TypeError: BinaryThresholdImageFilter.Execute() takes 2 positional arguments but 6 were given**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/niftymic_run_reconstruction_pipeline", line 33, in <module>
    sys.exit(load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_run_reconstruction_pipeline')())
  File "/NiftyMIC/niftymic/application/run_reconstruction_pipeline.py", line 295, in main
    raise RuntimeError("Reconstruction in subject space failed")
**RuntimeError: Reconstruction in subject space failed**

**Comment by SIGMACX** [comment]
Hi, I noticed you had a similar issue with the Execute() function in joint_image_mask_builder.py while running niftymic_run_reconstruction_pipeline. I'm currently facing the same error (TypeError: Execute() takes 2 positional arguments but 6 were given).

May I ask if you found a fix for it? 
Appreciate any insights you can share!
