### ISSUE TITLE
small bug in simulate_stacks_from_reconstruction

### ISSUE THREAD

**Issue by MrBurnst** [gift-surg/NiftyMIC#4]
with the option --reconstruction-mask and a mask that masks out slices at the top of the stack, 'simulate_slice' is left uninitialized:

`Traceback (most recent call last):
  File ".../NiftyMIC//niftymic/validation/simulate_stacks_from_reconstruction.py", line 168, in <module>
    main()
  File ".../NiftyMIC//niftymic/validation/simulate_stacks_from_reconstruction.py", line 126, in main
    simulated_slice.sitk_mask)
UnboundLocalError: local variable 'simulated_slice' referenced before assignment
`
I added a try-catch block, but there's prob. a better way of fixing this.

**Comment by renbem** [comment]
Thanks for pointing that out. Is fixed in the new version (v0.7.2).
